export const endpoints = {
  auth: {
    login: '/api/auth/login',
    adminLogin: '/api/auth/admin/login',
    refresh: '/api/auth/refresh',
    register: '/api/auth/register',
    logout: '/api/auth/logout',
    me: '/api/auth/me',
    profile: '/api/auth/profile',
    resendVerification: '/api/auth/resend-verification',
    favoriteGenres: '/api/users/favorite-genres',
    forgotPassword: '/api/auth/forgot-password',
    resetPassword: '/api/auth/reset-password',
    invitePreview: '/api/auth/invite/preview',
    inviteComplete: '/api/auth/invite/complete',
    confirmEmail: '/api/auth/confirm-email',
  },
  wishlist: {
    list: '/api/wishlist',
    add: '/api/wishlist',
    remove: (bookId: string) => `/api/wishlist/${bookId}`,
    check: (bookId: string) => `/api/wishlist/${bookId}/check`,
    count: '/api/wishlist/count',
  },
  analytics: {
    sales: '/api/analytics/sales',
    salesReport: '/api/analytics/sales/report',
    performance: '/api/analytics/performance',
    reviews: '/api/analytics/reviews',
  },
  seller: {
    profile: (userId: string) => `/api/seller/${userId}`,
    wallet: '/api/seller/wallet',
    earnings: '/api/seller/earnings',
    earningsSummary: '/api/seller/earnings/summary',
    withdrawals: '/api/seller/withdrawals',
  },
  library: {
    list: '/api/library',
    check: (bookFormatId: string) => `/api/library/check/${bookFormatId}`,
  },
  download: {
    book: (bookFormatId: string) => `/api/download/${bookFormatId}`,
  },
  reviews: {
    list: (bookId: string) => `/api/books/${bookId}/reviews`,
    can: (bookId: string) => `/api/books/${bookId}/reviews/can`,
    create: (bookId: string) => `/api/books/${bookId}/reviews`,
  },
  gamification: {
    me: '/api/gamification/me',
    activity: '/api/gamification/activity',
  },
  notifications: {
    list: '/api/notifications',
    unreadCount: '/api/notifications/unread-count',
    markAsRead: (id: string) => `/api/notifications/${id}/read`,
    markAllAsRead: '/api/notifications/read-all',
    dismissContext: '/api/notifications/dismiss-context',
    vapidPublicKey: '/api/notifications/vapid-public-key',
    subscribe: '/api/notifications/subscribe',
    unsubscribe: '/api/notifications/unsubscribe',
  },
  // NEW: Cart endpoints
  cart: {
    get: '/api/cart',
    addItem: '/api/cart/items',
    updateItem: (itemId: string) => `/api/cart/items/${itemId}`,
    removeItem: (itemId: string) => `/api/cart/items/${itemId}`,
    clear: '/api/cart',
  },
  // NEW: Checkout endpoints
  checkout: {
    initialize: '/api/checkout',
    verify: '/api/checkout/verify',
  },
    chat: {
    list: '/api/chat',
    direct: '/api/chat/direct',
    groups: '/api/chat/groups',
    detail: (chatId: string) => `/api/chat/${chatId}`,
    messages: (chatId: string) => `/api/chat/${chatId}/messages`,
    members: (chatId: string) => `/api/chat/${chatId}/members`,
    member: (chatId: string, memberId: string) => `/api/chat/${chatId}/members/${memberId}`,
    groupMembers: (chatId: string) => `/api/chat/groups/${chatId}/members`,
    groupMember: (chatId: string, memberId: string) =>
      `/api/chat/groups/${chatId}/members/${memberId}`,
    groupInvite: (chatId: string) => `/api/chat/groups/${chatId}/invite`,
    leaveGroup: (chatId: string) => `/api/chat/groups/${chatId}/leave`,
    deleteGroup: (chatId: string) => `/api/chat/groups/${chatId}`,
    deleteDirectChat: (chatId: string) => `/api/chat/direct/${chatId}`,
    join: (token: string) => `/api/chat/join/${token}`,
    joinPreview: (token: string) => `/api/chat/join/${token}/preview`,
    deleteMessageForMe: (messageId: string) => `/api/chat/messages/${messageId}/me`,
    deleteMessageForEveryone: (messageId: string) => `/api/chat/messages/${messageId}/everyone`,
    editMessage: (messageId: string) => `/api/chat/messages/${messageId}`,
  },
  feed: {
    list: '/api/feed',
    posts: '/api/feed/posts',
    uploadImage: '/api/feed/posts/upload-image',
    drafts: '/api/feed/drafts',
    myPosts: '/api/feed/my-posts',
    like: (postId: string) => `/api/feed/posts/${postId}/like`,
    share: (postId: string) => `/api/feed/posts/${postId}/share`,
    publish: (postId: string) => `/api/feed/drafts/${postId}/publish`,
    updateDraft: (postId: string) => `/api/feed/drafts/${postId}`,
    postDetail: (postId: string) => `/api/feed/posts/${postId}`,
    userPosts: (userId: string) => `/api/feed/users/${userId}/posts`,
    comments: (postId: string) => `/api/feed/posts/${postId}/comments`,
    createComment: (postId: string) => `/api/feed/posts/${postId}/comments`,
    likeComment: (commentId: string) => `/api/feed/comments/${commentId}/like`,
    reports: '/api/feed/reports',
  },
  profile: {
    me: '/api/profile',
    avatar: '/api/profile/avatar',
    settings: '/api/profile/settings',
    deleteAccount: '/api/profile/account',
    public: (username: string) => `/api/public/profile/${encodeURIComponent(username)}`,
    userPosts: (userId: string) => `/api/feed/users/${userId}/posts`,
  },
  follow: {
    follow: (userId: string) => `/api/follow/${userId}/follow`,
    unfollow: (userId: string) => `/api/follow/${userId}/follow`,
    isFollowing: (userId: string) => `/api/follow/${userId}/is-following`,
    followers: (userId: string) => `/api/follow/${userId}/followers`,
    following: (userId: string) => `/api/follow/${userId}/following`,
  },
  progress: {
    list: '/api/progress',
    forFormat: (bookFormatId: string) => `/api/progress/${bookFormatId}`,
    sync: '/api/progress/sync',
  },
  books: {
    list: '/api/books',
    detail: (id: string) => `/api/books/${id}`,
    genres: '/api/books/genres',
    languages: '/api/books/languages',
    personalized: '/api/books/personalized',
    search: '/api/books/search',
    myBooks: '/api/books/my-books',
    upload: '/api/books/upload',
    edit: (id: string) => `/api/books/${id}/edit`,
    updateUpload: (id: string) => `/api/books/${id}/upload`,
    addFormat: (id: string) => `/api/books/${id}/formats`,
    submit: (id: string) => `/api/books/${id}/submit`,
    formatById: (formatId: string) => `/api/books/formats/${formatId}`,
  },
  users: {
    search: '/api/users/search',
    presence: '/api/users/presence',
  },
} as const;